### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ghost**
Add provider directory rest client and merge with master

### CODE REVIEW

**Review by hendeavors — CHANGES_REQUESTED** [review]
Is it possible to have ProofingRestClient extend RestClient?

Leave the implements though.

**Comment by ghost** [comment]
Yeah. I was thinking the same thing. Can you add your tests to the repo so I can make sure they all still pass after the refactor?

**Comment by ghost** [comment]
Changes added. Wrote a test for session login which is passing.

**Comment by hendeavors** [comment]
Tests added

**Comment by ghost** [comment]
Updated with requested changes.

**Review by hendeavors — APPROVED** [review]

**Pull request merged**
